name: Build linux-arm64 artifacts

on: [push]

jobs:

  build-arm64-artifacts:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v3
      - name: Build
        run: yarn
