name: Build static site

on: [push]

jobs:

  build-static-site:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v3
      - name: Build
        run: |
                yarn
                yarn add next react react-dom
                npx next build && npx next export
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: site
           path: out # or path/to/artifact

