name: Build static site

on: [push]

jobs:

  build-static-site:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v3
      - name: Build
        run: |
                yarn
                rm .git -rf
                tar -cJf out.tar.xz *
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: site
           path: out.tar.xz # or path/to/artifact

